name: annflow

services:
  db:
    container_name: annflow-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: annflow
      POSTGRES_PASSWORD: postgres
    ports:
        - target: 5434
          published: 5434
    volumes:
        - postgres_data:/var/lib/postgresql/data

  php-cli:
    container_name: annflow-phpcli
    build:
      context: ./
      dockerfile: ./php-cli.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www/html/

  php-fpm:
    container_name: annflow-phpfpm
    build:
      context: ./
      dockerfile: ./php-fpm.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www/html/
    ports:
      - target: 9000
        published: 9000
    depends_on:
      - db

  nginx:
    container_name: annflow-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    environment:
      PHP_FPM_HOST: php-fpm
    ports:
      - target: 80
        published: 8082
    depends_on:
      - php-fpm

  composer:
    container_name: annflow-composer
    image: composer:2.6.6
    command: [ install, --ignore-platform-reqs ]
    volumes:
      - type: bind
        source: .
        target: /app

volumes:
  postgres_data: